packages:
  - apps/*
  - packages/*
  - contract
  - bridge
catalog:
  elysia: ^1.3.21
  '@trpc/server': ^11.5.0
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  '@types/node': ^22.13.11
  tsdown: ^0.15.5
  '@trpc/client': ^11.5.0
  '@prisma/client': ^6.15.0
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@reown/appkit'
  - '@stellar/stellar-sdk'
  - bigint-buffer
  - bufferutil
  - es5-ext
  - esbuild
  - keccak
  - prisma
  - secp256k1
  - sharp
  - utf-8-validate
